name: Auto Load Panel

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  load-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Load panel
        run: |
          npx puppeteer-core@latest --version
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            try {
              const browser = await puppeteer.launch({
                headless: 'new',
                args: ['--no-sandbox', '--disable-setuid-sandbox']
              });
              const page = await browser.newPage();
              console.log('🚀 Loading panel...');
              await page.goto('https://hypersignal-production.up.railway.app/signals');
              await page.waitForTimeout(10000);
              console.log('✅ Panel loaded successfully at', new Date().toISOString());
              await browser.close();
            } catch (error) {
              console.error('❌ Error:', error.message);
              process.exit(1);
            }
          })();
          "